GET http://localhost:8000/api/users

###

GET http://localhost:8000/api/users/3/  

###
POST http://localhost:8000/api/users/create/
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john.doe@example.com",
    "password": "password123"
}

###
POST http://localhost:8000/api/users/create/
Content-Type: application/json

{
    "name": "Tali kegunaan",
    "email": "tali.doe@gmail.com",
    "password": "assword098"
}

###
PUT   http://localhost:8000/api/users/3/
Content-Type: application/json

{
    "name": "Jin Wicked",
    "email": "jin.wicked@example.com",
    "password": "pfdsa3f3"
}

###
PATCH  http://localhost:8000/api/users/3/
Content-Type: application/json

{
    "name": "John Wicked"
}

###

DELETE  http://localhost:8000/api/users/4/