GET http://localhost:8080/api/employees

###

GET http://localhost:8080/api/employees/8f6994b6-caee-4957-946d-f812018af602

###
POST http://localhost:8080/api/employees
Content-Type: application/json

{
    "name": "Jane Doe",
    "email": "jane.doe@example.com",
    "phone": "5342532",
    "salary": 1553.10
}

###
PATCH  http://localhost:3000/users/679c11035f6a07b6a0de0183
Content-Type: application/json

{
    "name": "John Wicked"
}

###

DELETE  http://localhost:3000/users/679c0baa9301128095343c05